---
title: "First Knit"
author: "Giulianni"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct punctuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare English class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  

     I attended highschool in Los Alamitos, California. I graduated last year, being class of 2021. I personally think math was the better subject for me compared to english and peaked my interest a bit more. I'd say english falls into my understanding a bit better than math. The class I excelled most notably in was biology during my last year in highschool. Personally I find biology such an interesting subject, and enjoy the topics in it.


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I'm aware about the importance of needing a computer for this class, and I own a computer myself. My operating system on the computer is a windows 10. I'd put myself at a six out of ten in terms of computer knowledge, knowing I know the general information that people would know who owned a computer. I believe there's a lot I'm yet to learn about computers, and hope to learn more from this class. I do have a router at home and internet provided for me, as well as having a router extender near my computer just for better speeds. My connection to the internet is pretty good and stable for the most part, with little to no issues regarding my connection.  

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
  My name is Giulianni, Most people have trouble pronouncing my name, but it's something to pretty difficult to forget. Just for the sake of making it more convenient to pronounce and say regularly, I'd prefer being called my family nickname which would be Juju. 
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   
 
Generally something I'd want to achieve or accomplish would be a degree or some sort as well as a job that I love. I currently work at a veterinary hospital, and enjoy working in the environment, where I can make a difference. The subjects that come to mind would be Math and science. But in the long term I feel science would be something I'd want to further pursue. I would want various degrees by the time I'm finished with school. One for me would be obtaining my bachelors in Nursing, and eventually getting a Phd in Medicine.



## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   Yes, I've been to one, that being Mexico. One I'd definitely want to visit someday would be Greece, to view the scenery and enjoy a vacation. No, I've not enlisted in the military, but I've gave it a thought before. If I could choose a branch out of the few I'd most likely go with the navy, if I had gotten drafted. I'd go with the navy because I admire the Ocean, and I would like to be on the waters.




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 
I'm yet to complete Math 115 or 116. Currently I'm enrolled in Math 115 and looking forward to completing it. I initially wasn't aware about the differences of the classes, between Math 115 or 116. I'm aware now about the differences and potentially at some point complete both of the classes. I'm hoping and striving to get at least a 90 or above to satisfy myself and help me get toward the goals ahead of me. My plan is to just prioritize my courses as well as be organized with my schedule and eventually complete the course.





  




